# Copyright of Akshay Karjol and Kedar Rege
# Created Date - 2 NOV 2025
# For the project GPU_vs_CPU_AEB

# Parallel execution backends

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cpu_backend",
    hdrs = ["cpu_backend.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "gpu_backend",
    hdrs = ["gpu_backend.hpp"],
    visibility = ["//visibility:public"],
)