# Copyright of Akshay Karjol and Kedar Rege
# Created Date - 2 NOV 2025
# For the project GPU_vs_CPU_AEB

# Core solver mathematics library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "core",
    hdrs = ["state.hpp", "models.hpp", "rhs.hpp", "stepper.hpp"],
    visibility = ["//visibility:public"],
)