# Copyright of Akshay Karjol and Kedar Rege
# Created Date - 2 NOV 2025
# For the project GPU_vs_CPU_AEB

# Root BUILD file for the solver module

package(default_visibility = ["//visibility:public"])

config_setting(
    name = "cpu",
    values = {"define": "backend=cpu"},
)

config_setting(
    name = "gpu",
    values = {"define": "backend=gpu"},
)